services:
  analytics:
    container_name: analogdb-analytics
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8083:8080
      - 8084:8081 # metrics
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      KAFKA_TOPIC: ${KAFKA_TOPIC}
      KAFKA_BROKERS: ${KAFKA_BROKERS}
      KAFKA_CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_CONSUMER_GROUP: ${KAFKA_CONSUMER_GROUP}
      CLICKHOUSE_URL: ${CLICKHOUSE_URL}
      CLICKHOUSE_DB: ${CLICKHOUSE_DB}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_TABLE: events
      CLICKHOUSE_BATCH_SIZE: 1000
      CLICKHOUSE_FLUSH_INTERVAL_MS: 10000
      LOG_LEVEL: INFO
      APP_LOG_LEVEL: INFO
    depends_on:
      clickhouse:
        condition: service_healthy

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - 8123:8123 # HTTP
      - 9000:9000 # Native
    restart: unless-stopped
    environment:
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DB: ${CLICKHOUSE_DB}
      CLICKHOUSE_TABLE: ${CLICKHOUSE_TABLE}
    volumes:
      - clickhouse:/var/lib/clickhouse
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8123/ping",
        ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - analogdb

volumes:
  kafka:
  clickhouse:

networks:
  analogdb:
    external: true
    name: analogdb
