app:
  name: "analogdb"
  version: "0.1.0"
  env: "prod"
database:
  url: ""
redis:
  url: ""
  enabled: true
vector_database:
  host: ""
  scheme: "http"
http:
  port: "8080"
logger:
  level: "info"
  webhook: ""
auth:
  username: ""
  password: ""
