version: '3.7'
services:
    postgres:
        container_name: postgres
        image: postgres:latest
        restart: unless-stopped
        environment: 
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5438:5432'
        volumes:
          - ./postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
          - ./sql/populate.sql:/docker-entrypoint-initdb.d/populate.sql