version: '3.7'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=analog-local
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./sql/populate.sql:/docker-entrypoint-initdb.d/populate.sql

  web:
    container_name: analogdb
    build: .
    ports:
      - "5000:5000"
    restart: unless-stopped
    depends_on:
      - "postgres"
      
volumes:
  postgres: