version: "3.7"

services:
  analogdb:
    container_name: analogdb
    build: .
    ports:
      - 8080:${ANALOGDB_HTTP_PORT}
      - 9091:${ANALOGDB_METRICS_PORT}
    restart: unless-stopped
    environment:
      APP_NAME: ${ANALOGDB_APP_NAME}
      APP_VERSION: ${ANALOGDB_APP_VERSION}
      APP_ENV: ${ANALOGDB_APP_ENV}
      HTTP_PORT: ${ANALOGDB_HTTP_PORT}
      LOG_LEVEL: ${ANALOGDB_LOG_LEVEL}
      WEBHOOK_URL: ${ANALOGDB_WEBHOOK_URL}
      AUTH_USERNAME: ${ANALOGDB_AUTH_USERNAME}
      AUTH_PASSWORD: ${ANALOGDB_AUTH_PASSWORD}
      RATE_LIMIT_AUTH_USERNAME: ${ANALOGDB_RATE_LIMIT_AUTH_USERNAME}
      RATE_LIMIT_AUTH_PASSWORD: ${ANALOGDB_RATE_LIMIT_AUTH_PASSWORD}
      MIGRATION_ENABLED: ${ANALOGDB_MIGRATION_ENABLED}
      METRICS_ENABLED: ${ANALOGDB_METRICS_ENABLED}
      METRICS_PORT: ${ANALOGDB_METRICS_PORT}
      TRACING_ENABLED: ${ANALOGDB_TRACING_ENABLED}
      TRACING_ENDPOINT: ${ANALOGDB_TRACING_ENDPOINT}
      CACHE_ENABLED: ${ANALOGDB_CACHE_ENABLED}
      RATE_LIMIT_ENABLED: ${ANALOGDB_RATE_LIMIT_ENABLED}
      DATABASE_URL: ${POSTGRES_DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      VECTOR_DATABASE_HOST: ${WEAVIATE_HOST}
      VECTOR_DATABASE_SCHEME: ${WEAVIATE_SCHEME}
      KAFKA_ENABLED: ${ANALOGDB_KAFKA_ENABLED}
      KAFKA_TOPIC: ${KAFKA_TOPIC}
      KAFKA_BROKERS: ${KAFKA_BROKERS}
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy


  postgres:
    container_name: postgres
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PW}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - postgres:/var/lib/postgresql/data
      # - ./postgres/populate.sql:/docker-entrypoint-initdb.d/populate.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: "bitnami/redis:latest"
    container_name: "redis"
    environment:
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    # volumes:
    # - redis:/bitnami/redis/data

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    ports:
      - 9092:9092
    restart: unless-stopped
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092"
      KAFKA_LISTENERS: "CONTROLLER://kafka:29093,PLAINTEXT://kafka:29092,PLAINTEXT_HOST://0.0.0.0:9092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"
      KAFKA_LOG_DIRS: "/var/lib/kafka/data/kraft-combined-logs"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      # KRaft specific settings
      CLUSTER_ID: "${KAFKA_CLUSTER_ID}"
    volumes:
      - kafka:/var/lib/kafka/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "kafka-topics --bootstrap-server localhost:9092 --list || exit 1",
        ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 15s

  weaviate:
    image: semitechnologies/weaviate:1.18.3
    container_name: weaviate
    command:
      - --host
      - 0.0.0.0
      - --port
      - "8080"
      - --scheme
      - http
    ports:
      - 8081:8080
      - 2112:2112
    restart: unless-stopped
    environment:
      IMAGE_INFERENCE_API: "http://i2v-neural:8080"
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "img2vec-neural"
      ENABLE_MODULES: "img2vec-neural"
      CLUSTER_HOSTNAME: "node1"
      PROMETHEUS_MONITORING_ENABLED: "true"
      PROMETHEUS_MONITORING_PORT: 2112
      BACKUP_S3_BUCKET: ${WEAVIATE_BACKUP_S3_BUCKET}
      BACKUP_S3_PATH: ${WEAVIATE_BACKUP_S3_PATH}
      BACKUP_S3_ENDPOINT: ${WEAVIATE_BACKUP_S3_ENDPOINT}
      AWS_ACCESS_KEY_ID: ${WEAVIATE_AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${WEAVIATE_AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${WEAVIATE_AWS_REGION}
    volumes:
      - weaviate:/var/lib/weaviate

  i2v-neural:
    image: semitechnologies/img2vec-pytorch:resnet50
    container_name: weaviate-i2v
    ports:
      - 8082:8080
    restart: unless-stopped
    environment:
      ENABLE_CUDA: ${WEAVIATE_ENCODE_ENABLE_CUDA}

volumes:
  postgres:
  weaviate:
  # redis:
  kafka:

networks:
  default:
    external: true
    name: analogdb
