BEGIN;

ALTER TABLE pictures
ADD COLUMN c1_hex VARCHAR (12),
ADD COLUMN c1_css VARCHAR (50),
ADD COLUMN c1_percent NUMERIC (9, 8),
ADD COLUMN c2_hex VARCHAR (12),
ADD COLUMN c2_css VARCHAR (50),
ADD COLUMN c2_percent NUMERIC (9, 8),
ADD COLUMN c3_hex VARCHAR (12),
ADD COLUMN c3_css VARCHAR (50),
ADD COLUMN c3_percent NUMERIC (9, 8),
ADD COLUMN c4_hex VARCHAR (12),
ADD COLUMN c4_css VARCHAR (50),
ADD COLUMN c4_percent NUMERIC (9, 8),
ADD COLUMN c5_hex VARCHAR (12),
ADD COLUMN c5_css VARCHAR (50),
ADD COLUMN c5_percent NUMERIC (9, 8);

COMMIT;
