// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/cameras": {
            "get": {
                "description": "Retrieve cameras with optional query parameters for filtering and sorting",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cameras"
                ],
                "summary": "Get cameras with optional filtering",
                "parameters": [
                    {
                        "enum": [
                            "alphabetical",
                            "counts"
                        ],
                        "type": "string",
                        "description": "Sort order",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of results to return",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by camera make",
                        "name": "make",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by camera model",
                        "name": "model",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by specific camera ID",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Include count data",
                        "name": "include_counts",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Exclude zero counts",
                        "name": "exclude_zero_counts",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.CamerasResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid query parameters",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Create a new camera entry (requires authentication)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cameras"
                ],
                "summary": "Create a new camera",
                "parameters": [
                    {
                        "description": "camera data to create",
                        "name": "camera",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/analogdb.CreateCamera"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/server.CreateCameraResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "422": {
                        "description": "Unprocessable entity",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Create a new camera entry (requires authentication)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cameras"
                ],
                "summary": "Create a new camera",
                "parameters": [
                    {
                        "description": "camera data to create",
                        "name": "camera",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/analogdb.CreateCamera"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/server.CreateCameraResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "422": {
                        "description": "Unprocessable entity",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    }
                }
            }
        },
        "/films": {
            "get": {
                "description": "Retrieve films with optional query parameters for filtering and sorting",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "films"
                ],
                "summary": "Get films with optional filtering",
                "parameters": [
                    {
                        "enum": [
                            "alphabetical",
                            "counts"
                        ],
                        "type": "string",
                        "description": "Sort order",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of results to return",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by film make",
                        "name": "make",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by film type",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by film speed",
                        "name": "speed",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by color type",
                        "name": "colortype",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by specific film ID",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Include count data",
                        "name": "include_counts",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Exclude zero counts",
                        "name": "exclude_zero_counts",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.FilmsResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid query parameters",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Create a new film entry (requires authentication)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "films"
                ],
                "summary": "Create a new film",
                "parameters": [
                    {
                        "description": "Film data to create",
                        "name": "film",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/analogdb.CreateFilm"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/server.CreateFilmResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "422": {
                        "description": "Unprocessable entity",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Create a new film entry (requires authentication)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "films"
                ],
                "summary": "Create a new film",
                "parameters": [
                    {
                        "description": "Film data to create",
                        "name": "film",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/analogdb.CreateFilm"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/server.CreateFilmResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "422": {
                        "description": "Unprocessable entity",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "analogdb.Camera": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "string",
                    "example": "2025-07-11T12:00:00Z"
                },
                "description": {
                    "type": "string",
                    "example": "Nikon FM2 is a dependable SLR camera"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "make": {
                    "type": "string",
                    "example": "nikon"
                },
                "model": {
                    "type": "string",
                    "example": "fm2"
                },
                "post_count": {
                    "type": "integer",
                    "example": 50
                },
                "updated": {
                    "type": "string",
                    "example": "2025-07-11T12:00:00Z"
                }
            }
        },
        "analogdb.CreateCamera": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "Nikon FM2 is a dependable SLR camera"
                },
                "make": {
                    "type": "string",
                    "example": "nikon"
                },
                "model": {
                    "type": "string",
                    "example": "fm2"
                }
            }
        },
        "analogdb.CreateFilm": {
            "type": "object",
            "properties": {
                "color_type": {
                    "type": "string",
                    "example": "color"
                },
                "description": {
                    "type": "string",
                    "example": "Kodak Portra 400 is professional color negative film with fine grain"
                },
                "make": {
                    "type": "string",
                    "example": "kodak"
                },
                "speed": {
                    "type": "integer",
                    "example": 400
                },
                "type": {
                    "type": "string",
                    "example": "portra 400"
                }
            }
        },
        "analogdb.Error": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "not_found"
                },
                "message": {
                    "type": "string",
                    "example": "not found"
                }
            }
        },
        "analogdb.Film": {
            "type": "object",
            "properties": {
                "color_type": {
                    "type": "string"
                },
                "created": {
                    "type": "string",
                    "example": "2025-07-11T12:00:00Z"
                },
                "description": {
                    "type": "string",
                    "example": "Kodak Portra 400 is professional color negative film with fine grain"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "make": {
                    "type": "string",
                    "example": "kodak"
                },
                "post_count": {
                    "type": "integer",
                    "example": 25
                },
                "speed": {
                    "type": "integer",
                    "example": 400
                },
                "type": {
                    "type": "string",
                    "example": "portra 400"
                },
                "updated": {
                    "type": "string",
                    "example": "2025-07-11T12:00:00Z"
                }
            }
        },
        "server.CamerasResponse": {
            "type": "object",
            "properties": {
                "cameras": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/analogdb.Camera"
                    }
                }
            }
        },
        "server.CreateCameraResponse": {
            "type": "object",
            "properties": {
                "camera": {
                    "$ref": "#/definitions/analogdb.CreateCamera"
                },
                "message": {
                    "type": "string",
                    "example": "Success, camera created"
                }
            }
        },
        "server.CreateFilmResponse": {
            "type": "object",
            "properties": {
                "film": {
                    "$ref": "#/definitions/analogdb.CreateFilm"
                },
                "message": {
                    "type": "string",
                    "example": "Success, film created"
                }
            }
        },
        "server.FilmsResponse": {
            "type": "object",
            "properties": {
                "films": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/analogdb.Film"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "api.analogdb.com",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "AnalogDB API",
	Description:      "API for analogdb film database",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
