// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/extractions": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "List stored metadata extractions, newest post first (requires authentication)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "extractions"
                ],
                "summary": "List post metadata extractions",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Only extractions with or without unmatched mentions",
                        "name": "has_unmatched",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "camera",
                            "film"
                        ],
                        "type": "string",
                        "description": "Only extractions with an unmatched mention of this kind",
                        "name": "kind",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Only extractions with an unmatched mention with this normalized key",
                        "name": "key",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Include the input text and raw LLM output",
                        "name": "full",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Only post ids below this, for paging",
                        "name": "before_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "Number of results, at most 500",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.ExtractionsResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid query parameters",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Create or replace the stored metadata extraction of each post (requires authentication). Posts that don't exist are skipped.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "extractions"
                ],
                "summary": "Store post metadata extractions",
                "parameters": [
                    {
                        "description": "extractions to store, at most 500",
                        "name": "extractions",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.ExtractionsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.UpsertExtractionsResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid extractions",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "422": {
                        "description": "Unprocessable entity",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    }
                }
            }
        },
        "/camera": {
            "put": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Create a new camera entry (requires authentication)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "camera"
                ],
                "summary": "Create a new camera",
                "parameters": [
                    {
                        "description": "camera data to create",
                        "name": "camera",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/analogdb.CreateCamera"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/server.CreateCameraResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "422": {
                        "description": "Unprocessable entity",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Create a new camera entry (requires authentication)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "camera"
                ],
                "summary": "Create a new camera",
                "parameters": [
                    {
                        "description": "camera data to create",
                        "name": "camera",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/analogdb.CreateCamera"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/server.CreateCameraResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "422": {
                        "description": "Unprocessable entity",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    }
                }
            }
        },
        "/cameras": {
            "get": {
                "description": "Retrieve cameras with optional query parameters for filtering and sorting",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cameras"
                ],
                "summary": "Get cameras with optional filtering",
                "parameters": [
                    {
                        "enum": [
                            "alphabetical",
                            "counts"
                        ],
                        "type": "string",
                        "description": "Sort order",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of results to return",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by camera make",
                        "name": "make",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by camera model",
                        "name": "model",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by specific camera ID",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Include count data",
                        "name": "include_counts",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Exclude zero counts",
                        "name": "exclude_zero_counts",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Only return entries with at least this many posts, implies include_counts",
                        "name": "min_count",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Attach this many top scoring posts to each entry (1 to 10)",
                        "name": "top_posts",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.CamerasResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid query parameters",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    }
                }
            }
        },
        "/encode": {
            "put": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Encode posts to generate embeddings for similarity search. Supports both single post and batch encoding (requires authentication)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "similarity"
                ],
                "summary": "Encode posts for similarity matching",
                "parameters": [
                    {
                        "description": "Post IDs and batch size for encoding",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.encodePostsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.encodePostsResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "422": {
                        "description": "Unprocessable entity",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    }
                }
            }
        },
        "/film": {
            "put": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Create a new film entry (requires authentication)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "film"
                ],
                "summary": "Create a new film",
                "parameters": [
                    {
                        "description": "Film data to create",
                        "name": "film",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/analogdb.CreateFilm"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/server.CreateFilmResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "422": {
                        "description": "Unprocessable entity",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Create a new film entry (requires authentication)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "film"
                ],
                "summary": "Create a new film",
                "parameters": [
                    {
                        "description": "Film data to create",
                        "name": "film",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/analogdb.CreateFilm"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/server.CreateFilmResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "422": {
                        "description": "Unprocessable entity",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    }
                }
            }
        },
        "/films": {
            "get": {
                "description": "Retrieve films with optional query parameters for filtering and sorting",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "films"
                ],
                "summary": "Get films with optional filtering",
                "parameters": [
                    {
                        "enum": [
                            "alphabetical",
                            "counts"
                        ],
                        "type": "string",
                        "description": "Sort order",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of results to return",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by film make",
                        "name": "make",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by film type",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by film speed",
                        "name": "speed",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by color type",
                        "name": "colortype",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by specific film ID",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Include count data",
                        "name": "include_counts",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Exclude zero counts",
                        "name": "exclude_zero_counts",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Only return entries with at least this many posts, implies include_counts",
                        "name": "min_count",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Attach this many top scoring posts to each entry (1 to 10)",
                        "name": "top_posts",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.FilmsResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid query parameters",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    }
                }
            }
        },
        "/ids": {
            "get": {
                "description": "Retrieve a list of all post IDs in the system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "Get all post IDs",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.IDsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    }
                }
            }
        },
        "/keywords/summary": {
            "get": {
                "description": "Most common keywords with their post counts, optionally only from posts created in the last days",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "keywords"
                ],
                "summary": "Get keyword summary",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Number of keywords to return",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Only count keywords of posts created in the last days, 1 to 90",
                        "name": "days",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.KeywordsResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    }
                }
            }
        },
        "/post": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Create a new post with image analysis and similarity encoding (requires authentication)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "post"
                ],
                "summary": "Create a new post",
                "parameters": [
                    {
                        "description": "Post data to create",
                        "name": "post",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/analogdb.CreatePost"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/server.CreatePostResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "409": {
                        "description": "Post with permalink already exists",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "422": {
                        "description": "Unprocessable entity",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    }
                }
            }
        },
        "/post/{id}": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Get a post by ID from database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "post"
                ],
                "summary": "Get a post",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Post ID to get",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Post"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Delete a post by ID from database (requires authentication)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "post"
                ],
                "summary": "Delete a post",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Post ID to delete",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.DeleteResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Partially update a post's properties by ID (requires authentication)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "post"
                ],
                "summary": "Update a post",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Post ID to update",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Post fields to update",
                        "name": "post",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/analogdb.PatchPost"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.PatchResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "422": {
                        "description": "Unprocessable entity",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    }
                }
            }
        },
        "/post/{id}/similar": {
            "get": {
                "description": "Find posts similar to a given post using similarity matching",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "post"
                ],
                "summary": "Find similar posts",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Post ID to find similar posts for",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 12,
                        "description": "Maximum number of similar posts to return",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Include nsfw posts in query",
                        "name": "nsfw",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Include b\u0026w posts in query",
                        "name": "grayscale",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Include sprocketshot posts in query",
                        "name": "sprocket",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.SimilarPostsResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    }
                }
            }
        },
        "/posts": {
            "get": {
                "description": "Retrieve posts with optional query parameters for filtering by camera, film, keywords, etc. Supports pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "Get posts with optional filtering and pagination",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Number of posts per page",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Opaque cursor from next_cursor for the next page",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Deprecated: use cursor. Keyset from next_page_id, not supported with sort=random",
                        "name": "page_id",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "time",
                            "score",
                            "random"
                        ],
                        "type": "string",
                        "default": "time",
                        "description": "Sort order",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Random seed for consistent random sorting, picked from 1..500 when missing",
                        "name": "seed",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by post ID",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by post title",
                        "name": "title",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by author",
                        "name": "author",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by start time (unix timestamp)",
                        "name": "time_start",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by end time (unix timestamp)",
                        "name": "time_end",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by camera make",
                        "name": "camera_make",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by camera model",
                        "name": "camera_model",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by film make",
                        "name": "film_make",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by film type",
                        "name": "film_type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by film speed",
                        "name": "film_speed",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by focal length",
                        "name": "focal_length",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by aperture",
                        "name": "aperture",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filter by NSFW (true=only, false=exclude)",
                        "name": "nsfw",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filter by black and white (true=only, false=exclude)",
                        "name": "grayscale",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filter by sprocketshots (true=only, false=exclude)",
                        "name": "sprocket",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "description": "Filter by keywords (multiple allowed)",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "description": "Color filter (multiple allowed)",
                        "name": "color",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "number"
                        },
                        "collectionFormat": "multi",
                        "description": "Minimum color percentage (multiple allowed)",
                        "name": "min_color",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Minimum picture width",
                        "name": "width_min",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Maximum picture width",
                        "name": "width_max",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Minimum picture height",
                        "name": "height_min",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Maximum picture height",
                        "name": "height_max",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Minimum picture aspect ratio",
                        "name": "ratio_min",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Maximum picture aspect ratio",
                        "name": "ratio_max",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.PostResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    }
                }
            }
        },
        "/scrape/captions/missing": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "List ids of posts with no caption, or with a caption of another version when version is set (requires authentication)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scrape"
                ],
                "summary": "List posts missing a caption",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Caption version the posts should have",
                        "name": "version",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.CaptionsMissingResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    }
                }
            }
        },
        "/scrape/vectors/missing": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "List ids of posts with no object in the vector database, oldest first, and how many objects belong to deleted posts (requires authentication)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scrape"
                ],
                "summary": "List posts missing a vector",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.VectorsMissingResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "503": {
                        "description": "Vector database unavailable",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    }
                }
            }
        },
        "/search": {
            "get": {
                "description": "Hybrid search over image vectors, tags, captions and titles. Related keywords are returned on the first page only",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "Search posts by text",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search text, 1 to 200 characters",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Number of posts per page",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Opaque cursor from next_cursor for the next page",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filter by NSFW (true=only, false=exclude)",
                        "name": "nsfw",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filter by black and white (true=only, false=exclude)",
                        "name": "grayscale",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filter by sprocketshots (true=only, false=exclude)",
                        "name": "sprocket",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.SearchResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    }
                }
            }
        },
        "/search/image": {
            "post": {
                "description": "Find posts that look like an uploaded JPEG, PNG or WebP image of at most 5 MB. Returns one page",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "Search posts by image",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Image to search with",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Number of posts to return",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filter by NSFW (true=only, false=exclude)",
                        "name": "nsfw",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filter by black and white (true=only, false=exclude)",
                        "name": "grayscale",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filter by sprocketshots (true=only, false=exclude)",
                        "name": "sprocket",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.SearchResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "413": {
                        "description": "Image too large",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "415": {
                        "description": "Unsupported image type",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    },
                    "503": {
                        "description": "Too many image searches",
                        "schema": {
                            "$ref": "#/definitions/analogdb.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "analogdb.Camera": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "string",
                    "example": "2025-07-11T12:00:00Z"
                },
                "description": {
                    "type": "string",
                    "example": "Nikon FM2 is a dependable SLR camera"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "make": {
                    "type": "string",
                    "example": "nikon"
                },
                "model": {
                    "type": "string",
                    "example": "fm2"
                },
                "post_count": {
                    "type": "integer",
                    "example": 50
                },
                "slug": {
                    "type": "string",
                    "example": "nikon-fm2"
                },
                "top_posts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/analogdb.CatalogPost"
                    }
                },
                "updated": {
                    "type": "string",
                    "example": "2025-07-11T12:00:00Z"
                }
            }
        },
        "analogdb.CatalogPost": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "images": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/analogdb.Image"
                    }
                },
                "score": {
                    "type": "integer",
                    "example": 150
                },
                "title": {
                    "type": "string",
                    "example": "Sunset over the lake"
                }
            }
        },
        "analogdb.Color": {
            "type": "object",
            "properties": {
                "css": {
                    "type": "string",
                    "example": "dimgray"
                },
                "hex": {
                    "type": "string",
                    "example": "#837d5c"
                },
                "html": {
                    "type": "string",
                    "example": "gray"
                },
                "percent": {
                    "type": "number",
                    "example": 0.55
                }
            }
        },
        "analogdb.CreateCamera": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "Nikon FM2 is a dependable SLR camera"
                },
                "make": {
                    "type": "string",
                    "example": "nikon"
                },
                "model": {
                    "type": "string",
                    "example": "fm2"
                }
            }
        },
        "analogdb.CreateFilm": {
            "type": "object",
            "properties": {
                "color_type": {
                    "type": "string",
                    "example": "color"
                },
                "description": {
                    "type": "string",
                    "example": "Kodak Portra 400 is professional color negative film with fine grain"
                },
                "make": {
                    "type": "string",
                    "example": "kodak"
                },
                "speed": {
                    "type": "integer",
                    "example": 400
                },
                "type": {
                    "type": "string",
                    "example": "portra 400"
                }
            }
        },
        "analogdb.CreatePost": {
            "type": "object",
            "properties": {
                "aperture": {
                    "type": "string",
                    "example": "f/2.0"
                },
                "author": {
                    "type": "string",
                    "example": "thecameraman"
                },
                "camera_make": {
                    "type": "string",
                    "example": "nikon"
                },
                "camera_model": {
                    "type": "string",
                    "example": "fm2"
                },
                "caption": {
                    "$ref": "#/definitions/analogdb.PostCaption"
                },
                "colors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/analogdb.Color"
                    }
                },
                "description": {
                    "type": "string",
                    "example": "My favorite camera and film combo on 35mm at f/2.0"
                },
                "film_make": {
                    "type": "string",
                    "example": "kodak"
                },
                "film_speed": {
                    "type": "integer",
                    "example": 400
                },
                "film_type": {
                    "type": "string",
                    "example": "color"
                },
                "focal_length": {
                    "type": "integer",
                    "example": 35
                },
                "grayscale": {
                    "type": "boolean",
                    "example": false
                },
                "images": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/analogdb.Image"
                    }
                },
                "keywords": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/analogdb.Keyword"
                    }
                },
                "nsfw": {
                    "type": "boolean",
                    "example": false
                },
                "permalink": {
                    "type": "string",
                    "example": "https://www.reddit.com/r/analog/comments/1/post"
                },
                "score": {
                    "type": "integer",
                    "example": 1000
                },
                "sprocket": {
                    "type": "boolean",
                    "example": false
                },
                "timestamp": {
                    "type": "integer",
                    "example": 1752354541
                },
                "title": {
                    "type": "string",
                    "example": "A day at the fields [Nikon FM2 | Portra 400]"
                }
            }
        },
        "analogdb.Error": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "not_found"
                },
                "message": {
                    "type": "string",
                    "example": "not found"
                }
            }
        },
        "analogdb.Film": {
            "type": "object",
            "properties": {
                "color_type": {
                    "type": "string",
                    "example": "color"
                },
                "created": {
                    "type": "string",
                    "example": "2025-07-11T12:00:00Z"
                },
                "description": {
                    "type": "string",
                    "example": "Kodak Portra 400 is professional color negative film with fine grain"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "make": {
                    "type": "string",
                    "example": "kodak"
                },
                "post_count": {
                    "type": "integer",
                    "example": 25
                },
                "slug": {
                    "type": "string",
                    "example": "kodak-portra-400"
                },
                "speed": {
                    "type": "integer",
                    "example": 400
                },
                "top_posts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/analogdb.CatalogPost"
                    }
                },
                "type": {
                    "type": "string",
                    "example": "portra 400"
                },
                "updated": {
                    "type": "string",
                    "example": "2025-07-11T12:00:00Z"
                }
            }
        },
        "analogdb.Image": {
            "type": "object",
            "properties": {
                "height": {
                    "type": "integer",
                    "example": 7600
                },
                "resolution": {
                    "type": "string",
                    "example": "high"
                },
                "url": {
                    "type": "string",
                    "example": "https://cloudfront.net/1.jpeg"
                },
                "width": {
                    "type": "integer",
                    "example": 4800
                }
            }
        },
        "analogdb.Keyword": {
            "type": "object",
            "properties": {
                "weight": {
                    "type": "number",
                    "example": 0.43
                },
                "word": {
                    "type": "string",
                    "example": "baseball"
                }
            }
        },
        "analogdb.KeywordSummary": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer",
                    "example": 207
                },
                "word": {
                    "type": "string",
                    "example": "baseball"
                }
            }
        },
        "analogdb.PatchPost": {
            "type": "object",
            "properties": {
                "aperture": {
                    "type": "string",
                    "example": "f/2.4"
                },
                "camera_make": {
                    "type": "string",
                    "example": "canon"
                },
                "camera_model": {
                    "type": "string",
                    "example": "ae-1"
                },
                "caption": {
                    "$ref": "#/definitions/analogdb.PostCaption"
                },
                "clear": {
                    "description": "Clear sets these metadata fields to null",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "film_speed"
                    ]
                },
                "colors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/analogdb.Color"
                    }
                },
                "description": {
                    "type": "string",
                    "example": "New description"
                },
                "film_make": {
                    "type": "string",
                    "example": "kodak"
                },
                "film_speed": {
                    "type": "integer",
                    "example": 200
                },
                "film_type": {
                    "type": "string",
                    "example": "gold 200"
                },
                "focal_length": {
                    "type": "integer",
                    "example": 50
                },
                "grayscale": {
                    "type": "boolean",
                    "example": false
                },
                "keywords": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/analogdb.Keyword"
                    }
                },
                "nsfw": {
                    "type": "boolean",
                    "example": true
                },
                "score": {
                    "type": "integer",
                    "example": 1010
                },
                "sprocket": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "analogdb.Post": {
            "type": "object",
            "properties": {
                "aperture": {
                    "type": "string",
                    "example": "f/2.0"
                },
                "author": {
                    "type": "string",
                    "example": "thecameraman"
                },
                "camera_make": {
                    "type": "string",
                    "example": "nikon"
                },
                "camera_model": {
                    "type": "string",
                    "example": "fm2"
                },
                "caption": {
                    "type": "string",
                    "example": "A woman on a beach at sunset"
                },
                "colors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/analogdb.Color"
                    }
                },
                "created": {
                    "description": "time the post was added to analogdb",
                    "type": "string",
                    "example": "2025-07-11T12:00:00Z"
                },
                "description": {
                    "type": "string",
                    "example": "My favorite camera and film combo on 35mm at f/2.0"
                },
                "film_make": {
                    "type": "string",
                    "example": "kodak"
                },
                "film_speed": {
                    "type": "integer",
                    "example": 400
                },
                "film_type": {
                    "type": "string",
                    "example": "color"
                },
                "focal_length": {
                    "type": "integer",
                    "example": 35
                },
                "grayscale": {
                    "type": "boolean",
                    "example": false
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "images": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/analogdb.Image"
                    }
                },
                "keywords": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/analogdb.Keyword"
                    }
                },
                "nsfw": {
                    "type": "boolean",
                    "example": false
                },
                "permalink": {
                    "type": "string",
                    "example": "https://www.reddit.com/r/analog/comments/1/post"
                },
                "score": {
                    "type": "integer",
                    "example": 1000
                },
                "sprocket": {
                    "type": "boolean",
                    "example": false
                },
                "timestamp": {
                    "type": "integer",
                    "example": 1752354541
                },
                "title": {
                    "type": "string",
                    "example": "A day at the fields [Nikon FM2 | Portra 400]"
                },
                "updated": {
                    "description": "time the post was last changed in analogdb",
                    "type": "string",
                    "example": "2025-07-11T12:00:00Z"
                }
            }
        },
        "analogdb.PostCaption": {
            "type": "object",
            "properties": {
                "caption": {
                    "type": "string",
                    "example": "A woman on a beach at sunset"
                },
                "model": {
                    "type": "string",
                    "example": "google/gemini-2.5-flash-lite"
                },
                "raw": {
                    "type": "object"
                },
                "version": {
                    "type": "string",
                    "example": "v1"
                }
            }
        },
        "analogdb.PostExtraction": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "string"
                },
                "extractor_version": {
                    "type": "string",
                    "example": "2026-10-a"
                },
                "input": {
                    "type": "string",
                    "example": "title: Dusk [Nikon FM, Portra 400]"
                },
                "input_hash": {
                    "type": "string",
                    "example": "9f2c..."
                },
                "model": {
                    "type": "string",
                    "example": "google/gemini-2.5-flash-lite"
                },
                "post_id": {
                    "type": "integer",
                    "example": 1234
                },
                "raw": {
                    "type": "object"
                },
                "unmatched": {
                    "type": "array",
                    "items": {
                        "type": "object"
                    }
                },
                "updated": {
                    "type": "string"
                }
            }
        },
        "server.CamerasResponse": {
            "type": "object",
            "properties": {
                "cameras": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/analogdb.Camera"
                    }
                }
            }
        },
        "server.CaptionsMissingResponse": {
            "type": "object",
            "properties": {
                "ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        1,
                        2,
                        3
                    ]
                }
            }
        },
        "server.CreateCameraResponse": {
            "type": "object",
            "properties": {
                "camera": {
                    "$ref": "#/definitions/analogdb.CreateCamera"
                },
                "message": {
                    "type": "string",
                    "example": "Success, camera created"
                }
            }
        },
        "server.CreateFilmResponse": {
            "type": "object",
            "properties": {
                "film": {
                    "$ref": "#/definitions/analogdb.CreateFilm"
                },
                "message": {
                    "type": "string",
                    "example": "Success, film created"
                }
            }
        },
        "server.CreatePostResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Success, post created"
                },
                "post": {
                    "$ref": "#/definitions/analogdb.Post"
                }
            }
        },
        "server.DeleteResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Success, post deleted"
                }
            }
        },
        "server.ExtractionsRequest": {
            "type": "object",
            "properties": {
                "extractions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/analogdb.PostExtraction"
                    }
                }
            }
        },
        "server.ExtractionsResponse": {
            "type": "object",
            "properties": {
                "extractions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/analogdb.PostExtraction"
                    }
                },
                "next_before_id": {
                    "type": "integer",
                    "example": 1200
                }
            }
        },
        "server.FilmsResponse": {
            "type": "object",
            "properties": {
                "films": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/analogdb.Film"
                    }
                }
            }
        },
        "server.IDsResponse": {
            "type": "object",
            "properties": {
                "ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        1,
                        2,
                        3,
                        4,
                        5
                    ]
                }
            }
        },
        "server.KeywordsResponse": {
            "type": "object",
            "properties": {
                "keywords": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/analogdb.KeywordSummary"
                    }
                }
            }
        },
        "server.Meta": {
            "type": "object",
            "properties": {
                "next_cursor": {
                    "description": "Opaque cursor for the next page, empty at the end",
                    "type": "string",
                    "example": "eyJzIjoidGltZSIsInYiOjE3NTIyNDQxMTYsImlkIjo0MDIxMX0"
                },
                "next_page_id": {
                    "description": "Deprecated: use next_cursor",
                    "type": "integer",
                    "example": 1752244116
                },
                "next_page_url": {
                    "type": "string",
                    "example": "/posts?cursor=eyJzIjoidGltZSIsInYiOjE3NTIyNDQxMTYsImlkIjo0MDIxMX0\u0026page_size=20\u0026sort=time"
                },
                "page_size": {
                    "type": "integer",
                    "example": 20
                },
                "seed": {
                    "type": "integer",
                    "example": 37
                },
                "total_posts": {
                    "type": "integer",
                    "example": 200
                }
            }
        },
        "server.PatchResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Success, post patched"
                }
            }
        },
        "server.PostResponse": {
            "type": "object",
            "properties": {
                "meta": {
                    "$ref": "#/definitions/server.Meta"
                },
                "posts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/analogdb.Post"
                    }
                }
            }
        },
        "server.SearchMeta": {
            "type": "object",
            "properties": {
                "next_cursor": {
                    "description": "Opaque cursor for the next page, empty at the end",
                    "type": "string",
                    "example": "eyJvIjo1MH0"
                },
                "next_page_url": {
                    "type": "string",
                    "example": "/search?cursor=eyJvIjo1MH0\u0026page_size=50\u0026q=girl+at+sunset"
                },
                "page_size": {
                    "type": "integer",
                    "example": 50
                }
            }
        },
        "server.SearchResponse": {
            "type": "object",
            "properties": {
                "meta": {
                    "$ref": "#/definitions/server.SearchMeta"
                },
                "posts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/analogdb.Post"
                    }
                },
                "related_keywords": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "beach",
                        "silhouette",
                        "dusk"
                    ]
                }
            }
        },
        "server.SimilarPostsResponse": {
            "type": "object",
            "properties": {
                "posts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/analogdb.Post"
                    }
                }
            }
        },
        "server.UpsertExtractionsResponse": {
            "type": "object",
            "properties": {
                "skipped": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        1234
                    ]
                },
                "written": {
                    "type": "integer",
                    "example": 499
                }
            }
        },
        "server.VectorsMissingResponse": {
            "type": "object",
            "properties": {
                "extra": {
                    "type": "integer",
                    "example": 0
                },
                "ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        1,
                        2,
                        3
                    ]
                }
            }
        },
        "server.encodePostsRequest": {
            "type": "object",
            "properties": {
                "batch_size": {
                    "type": "integer",
                    "example": 20
                },
                "ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "server.encodePostsResponse": {
            "type": "object",
            "properties": {
                "failed_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "successfully encoded 5 posts"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "api.analogdb.com",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "AnalogDB API",
	Description:      "API for analogdb film database",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
