CREATE TABLE IF NOT EXISTS colors(
id SERIAL PRIMARY KEY,
hex VARCHAR(10) NOT NULL,
css VARCHAR(255) NOT NULL,
html VARCHAR(255) NOT NULL,
percent NUMERIC(9, 8),
post_id INT NOT NULL,
CONSTRAINT fk_post_id
	FOREIGN KEY(post_id)
		REFERENCES pictures(id)
			ON DELETE CASCADE
);
