-- Deterministic synthetic data for benchmarking post queries.
-- Run against a migrated schema. Existing rows are removed.
-- psql -v posts=100000 -f bench/seed.sql
\set ON_ERROR_STOP on
\if :{?posts}
\else
\set posts 100000
\endif

BEGIN;

TRUNCATE pictures, keywords, colors, post_updates, cameras, films RESTART IDENTITY CASCADE;

SELECT setseed(0.42);

-- cameras and films from scrape/data/cameras.json and scrape/data/films.json
CREATE TEMP TABLE bench_cameras (camera_make text, camera_model text) ON COMMIT DROP;
INSERT INTO bench_cameras (camera_make, camera_model) VALUES
('argus', 'c4'),
('bronica', 'ec'),
('bronica', 'etr'),
('bronica', 'etrs'),
('bronica', 'gs-1'),
('bronica', 'rf645'),
('bronica', 's2'),
('bronica', 'sq-a'),
('canon', '1n'),
('canon', 'a-1'),
('canon', 'ae-1'),
('canon', 'ae-1 program'),
('canon', 'af35m'),
('canon', 'autoboy s'),
('canon', 'av-1'),
('canon', 'canonet ql17 giii'),
('canon', 'canonet ql19'),
('canon', 'demi ee17'),
('canon', 'ef'),
('canon', 'elan'),
('canon', 'elan 7e'),
('canon', 'elan ii'),
('canon', 'eos 1'),
('canon', 'eos 100'),
('canon', 'eos 1n'),
('canon', 'eos 1v'),
('canon', 'eos 3'),
('canon', 'eos 30'),
('canon', 'eos 300'),
('canon', 'eos 33'),
('canon', 'eos 5'),
('canon', 'eos 50'),
('canon', 'eos 650'),
('canon', 'eos rebel g'),
('canon', 'eos rebel ti'),
('canon', 'f-1'),
('canon', 'ftb'),
('canon', 'fx'),
('canon', 'new f-1'),
('canon', 'p'),
('canon', 'prima super 115'),
('canon', 'rebel 2000'),
('canon', 'rebel ti'),
('canon', 'sure shot'),
('canon', 'sure shot z115'),
('canon', 't90'),
('chamonix', '45N-1 Classic'),
('chamonix', '810 Alpinist X'),
('chinon industries inc.', '3001'),
('chinon industries inc.', 'm-4'),
('contax', '139 quartz'),
('contax', '645'),
('contax', 'g1'),
('contax', 'g2'),
('contax', 'iiia'),
('contax', 'rts'),
('contax', 'rts ii'),
('contax', 's2'),
('contax', 't2'),
('contax', 't3'),
('contax', 'tvs'),
('exakta', 'hs-10'),
('exakta', 'vx'),
('film laundry', 'eb 617 mk ii'),
('franka', 'solida ii'),
('fujifilm', 'az-1'),
('fujifilm', 'ga645'),
('fujifilm', 'ga645i'),
('fujifilm', 'gf670w'),
('fujifilm', 'gs645w'),
('fujifilm', 'gsw690'),
('fujifilm', 'gsw690ii'),
('fujifilm', 'gsw690iii'),
('fujifilm', 'gw690'),
('fujifilm', 'gw690ii'),
('fujifilm', 'gw690iii'),
('fujifilm', 'gx680'),
('fujifilm', 'instax mini 90'),
('fujifilm', 'instax mini 99'),
('fujifilm', 'klasse s'),
('fujifilm', 'klasse w'),
('fujifilm', 'st801'),
('fujifilm', 'tx-1'),
('graflex', 'pacemaker 45 crown graphic'),
('graflex', 'speed graphic'),
('hasselblad', '203fe'),
('hasselblad', '500c'),
('hasselblad', '500c/m'),
('hasselblad', '501cm'),
('hasselblad', '503cx'),
('hasselblad', 'h2'),
('hasselblad', 'swc'),
('hasselblad', 'xpan'),
('holga', '120n'),
('intrepid camera', '4x5'),
('kiev', '88'),
('kodak', 'ektar h35'),
('kodak', 'retina iii'),
('konica', 'auto s3'),
('konica', 'c35'),
('konica', 'c35 automatic'),
('konica', 'c35 flashmatic'),
('konica', 'hexar af'),
('konica', 'hexar rf'),
('konica', 't4'),
('kowa', 'six'),
('leica', 'cl'),
('leica', 'iiig'),
('leica', 'm2'),
('leica', 'm3'),
('leica', 'm4'),
('leica', 'm4-p'),
('leica', 'm5'),
('leica', 'm6'),
('leica', 'm7'),
('leica', 'mp'),
('leica', 'r6.2'),
('linhof', 'master technika'),
('lomography', 'sprocket rocket'),
('mamiya', '23'),
('mamiya', '6'),
('mamiya', '645'),
('mamiya', '645 super'),
('mamiya', '7'),
('mamiya', '7ii'),
('mamiya', 'c220'),
('mamiya', 'c3'),
('mamiya', 'c330'),
('mamiya', 'msx500'),
('mamiya', 'press'),
('mamiya', 'rb67'),
('mamiya', 'rb67 pro sd'),
('mamiya', 'rb67 pro-s'),
('mamiya', 'rz67'),
('mamiya', 'rz67 pro ii'),
('mamiya', 'super 23'),
('minolta', 'autocord'),
('minolta', 'cle'),
('minolta', 'dynax 7xi'),
('minolta', 'dynax 800si'),
('minolta', 'hi-matic 7sii'),
('minolta', 'hi-matic af'),
('minolta', 'hi-matic af2'),
('minolta', 'maxxum 7000'),
('minolta', 'maxxum htsi+'),
('minolta', 'sr-7'),
('minolta', 'srt 200'),
('minolta', 'srt-101'),
('minolta', 'srt201'),
('minolta', 'tc-1'),
('minolta', 'vectis s-1'),
('minolta', 'vectis s-100'),
('minolta', 'x-370s'),
('minolta', 'x-500'),
('minolta', 'x-570'),
('minolta', 'x-700'),
('minolta', 'xd-s'),
('minolta', 'xd11'),
('minolta', 'xd5'),
('minolta', 'xd7'),
('minolta', 'xe-7'),
('minolta', 'xg1'),
('minox', '35 gt-x'),
('nikon', 'el2'),
('nikon', 'em'),
('nikon', 'f'),
('nikon', 'f100'),
('nikon', 'f2'),
('nikon', 'f3'),
('nikon', 'f4'),
('nikon', 'f5'),
('nikon', 'f501'),
('nikon', 'f6'),
('nikon', 'f60'),
('nikon', 'f601'),
('nikon', 'f65'),
('nikon', 'f80'),
('nikon', 'f90'),
('nikon', 'f90s'),
('nikon', 'fa'),
('nikon', 'fe'),
('nikon', 'fe2'),
('nikon', 'fg'),
('nikon', 'fg-20'),
('nikon', 'fm'),
('nikon', 'fm2'),
('nikon', 'fm3a'),
('nikon', 'l35af'),
('nikon', 'n2000'),
('nikon', 'n2020'),
('nikon', 'n6006'),
('nikon', 'nikkormat el'),
('nikon', 'onetouch af35'),
('nikon', 's2'),
('nikon', 's3'),
('nikon', 'sp'),
('nikonos', 'i'),
('nikonos', 'ii'),
('nikonos', 'iii'),
('nikonos', 'iv-a'),
('nikonos', 'rs af'),
('nikonos', 'v'),
('noble design', 'ND 6x17 Pro'),
('olympus', '35 rc'),
('olympus', '35 rd'),
('olympus', '35 sp'),
('olympus', 'af-1'),
('olympus', 'af-10'),
('olympus', 'infinity twin'),
('olympus', 'infinity zoom'),
('olympus', 'mju i'),
('olympus', 'mju ii'),
('olympus', 'om-1'),
('olympus', 'om-10'),
('olympus', 'om-1n'),
('olympus', 'om-2'),
('olympus', 'om-2n'),
('olympus', 'om-3'),
('olympus', 'om-4'),
('olympus', 'om-40'),
('olympus', 'pen ee'),
('olympus', 'pen f'),
('olympus', 'pen ft'),
('olympus', 'stylus'),
('olympus', 'stylus epic'),
('olympus', 'stylus zoom'),
('olympus', 'trip 35'),
('olympus', 'xa'),
('olympus', 'xa2'),
('olympus', 'xa3'),
('olympus', 'xa4'),
('pentax', '17'),
('pentax', '645'),
('pentax', '67'),
('pentax', '67 ii'),
('pentax', 'espio 70'),
('pentax', 'iqzoom'),
('pentax', 'k1000'),
('pentax', 'k2'),
('pentax', 'km'),
('pentax', 'kx'),
('pentax', 'lx'),
('pentax', 'me super'),
('pentax', 'me super se'),
('pentax', 'mx'),
('pentax', 'mz-s'),
('pentax', 'program plus'),
('pentax', 'spotmatic'),
('pentax', 'super program'),
('pentax', 'super-a'),
('pentax', 'zxm'),
('petri', '7s ii'),
('phenix', 'dc 303'),
('polaroid', 'big shot'),
('polaroid', 'sx-70'),
('praktica', 'bms'),
('praktica', 'l2'),
('praktica', 'ltl3'),
('ricoh', '35'),
('ricoh', '35r'),
('ricoh', '500'),
('ricoh', 'gr1s'),
('ricoh', 'kr-5 super ii'),
('ricoh', 'xr-2'),
('rollei', '35'),
('rollei', '35s'),
('rollei', '35t'),
('rollei', '6008'),
('rollei', 'rolleicord'),
('rollei', 'rolleicord ii'),
('rollei', 'rolleicord iii'),
('rollei', 'rolleicord iv'),
('rollei', 'rolleicord v'),
('rollei', 'rolleiflex 2.8f'),
('rollei', 'rolleiflex 2.8gx'),
('rollei', 'rolleiflex 3.5f'),
('rollei', 'rolleiflex 3.5t'),
('rollei', 'rolleiflex automat k4b'),
('rollei', 'rolleiflex tlr'),
('rollei', 'sl35'),
('rollei', 'sle35e'),
('samsung', 'ecx 1'),
('shanghai camera factory', 'seagull 4a'),
('topcon', 'super dm'),
('toyo', 'view 45c'),
('tronic', 'af 3590'),
('vivitar', '220/sl'),
('vivitar', '35cs'),
('vivitar', 'tec 45'),
('vivitar', 'v3800n'),
('vivitar', 'xc-3'),
('vivitar', 'xv-5'),
('voigtländer', 'bessa 66'),
('voigtländer', 'bessa l'),
('voigtländer', 'bessa r2'),
('voigtländer', 'bessa r2a'),
('voigtländer', 'bessa r2m'),
('voigtländer', 'bessa r3m'),
('voigtländer', 'bessa r4a'),
('voigtländer', 'perkeo ii'),
('voigtländer', 'vitessa'),
('wista', '45'),
('yashica', '635'),
('yashica', 'electro 35'),
('yashica', 'em'),
('yashica', 'fx-3'),
('yashica', 'fx-3 super 2000'),
('yashica', 'mat-124g'),
('yashica', 't4'),
('yashica', 't5'),
('zeiss ikon', 'contaflex'),
('zeiss ikon', 'contessa'),
('zeiss ikon', 'ikoflex ic'),
('zeiss ikon', 'ikoflex iia'),
('zeiss ikon', 'ikonta 521'),
('zeiss ikon', 'nettar'),
('zeiss ikon', 'zm'),
('zenit', '12'),
('zenit', '122'),
('zenit', 'e'),
('zenit', 'ttl'),
('zorki', '4');

CREATE TEMP TABLE bench_films (film_make text, film_type text, film_speed int, color_type text) ON COMMIT DROP;
INSERT INTO bench_films (film_make, film_type, film_speed, color_type) VALUES
('adox', 'cms 20', 20, 'bw'),
('adox', 'scala 160', 160, 'bw'),
('adox', 'silvermax', 100, 'bw'),
('agfa', 'agfacolor optima prestige ii 100', 100, 'color'),
('agfa', 'agfacolor optima prestige ii 400', 400, 'color'),
('agfa', 'optima 100', 100, 'color'),
('agfa', 'optima 200', 200, 'color'),
('agfa', 'optima 400', 400, 'color'),
('agfa', 'vista plus 200', 200, 'color'),
('agfa', 'vista plus 400', 400, 'color'),
('agfaphoto', 'apx 100', 100, 'bw'),
('agfaphoto', 'apx 400', 400, 'bw'),
('agfaphoto', 'aviphot pan 200', 200, 'bw'),
('agfaphoto', 'aviphot pan 80', 80, 'bw'),
('agfaphoto', 'color 400', 400, 'color'),
('agfaphoto', 'ct precisa', 100, 'color'),
('arista', 'edu ultra 100', 100, 'bw'),
('arista', 'edu ultra 200', 200, 'bw'),
('arista', 'edu ultra 400', 400, 'bw'),
('arista', 'ortho litho 3.0', 3, 'bw'),
('astrum', 'foto 100', 100, 'bw'),
('astrum', 'foto 200', 200, 'bw'),
('astrum', 'foto 400', 400, 'bw'),
('bergger', 'pancro 400', 400, 'bw'),
('bt21', 'star 400', 400, 'color'),
('budachrome', 'daydream', 250, 'color'),
('budachrome', 'mono', 200, 'bw'),
('budachrome', 'night shift', 500, 'color'),
('candido', '200', 200, 'color'),
('candido', '400', 400, 'color'),
('candido', '800', 800, 'color'),
('catlabs', 'x film 320', 320, 'bw'),
('catlabs', 'x film 80', 80, 'bw'),
('china lucky film', 'lucky color 200', 200, 'color'),
('cinestill', '400d', 400, 'color'),
('cinestill', '50d', 50, 'color'),
('cinestill', '800t', 800, 'color'),
('cinestill', 'bwxx', 250, 'bw'),
('cinestill', 'red rum', 200, 'color'),
('dubblefilm', 'apollo 200', 200, 'color'),
('dubblefilm', 'apollo 400', 400, 'color'),
('dubblefilm', 'bubblegum 200', 200, 'color'),
('dubblefilm', 'jelly 200', 200, 'color'),
('dubblefilm', 'jelly 400', 400, 'color'),
('dubblefilm', 'pacific 200', 200, 'color'),
('dubblefilm', 'pacific 400', 400, 'color'),
('dubblefilm', 'stereo 200', 200, 'color'),
('dubblefilm', 'stereo 400', 400, 'color'),
('film ferrania', 'orto', 50, 'bw'),
('film ferrania', 'p30', 80, 'bw'),
('film ferrania', 'p33', 160, 'bw'),
('film ferrania', 'solaris 100', 100, 'color'),
('film photography project', 'derev pan 400', 400, 'bw'),
('film photography project', 'dracula 35', 64, 'bw'),
('film photography project', 'eastman double-x', 200, 'bw'),
('film photography project', 'low iso b&w', 6, 'bw'),
('film photography project', 'low iso c', 1, 'color'),
('film photography project', 'sonic 25', 25, 'bw'),
('film photography project', 'wolfman 120', 100, 'bw'),
('film photography project', 'wolfman 35', 100, 'bw'),
('film photography project', 'x-ray', 200, 'bw'),
('film washi', 'a', 12, 'bw'),
('film washi', 'd', 500, 'bw'),
('film washi', 'e', 3, 'bw'),
('film washi', 'f', 100, 'bw'),
('film washi', 'i', 80, 'bw'),
('film washi', 'k', 100, 'bw'),
('film washi', 'r', 100, 'bw'),
('film washi', 's', 50, 'bw'),
('film washi', 'v', 100, 'bw'),
('film washi', 'w', 25, 'bw'),
('film washi', 'x', 100, 'color'),
('film washi', 'y', 100, 'bw'),
('film washi', 'z', 400, 'bw'),
('flic film', 'apollo 18', 400, 'color'),
('flic film', 'atm 400', 400, 'bw'),
('flic film', 'aurora 400', 400, 'color'),
('flic film', 'aurora 800', 800, 'color'),
('flic film', 'chrome 100', 100, 'color'),
('flic film', 'elektra 100', 100, 'color'),
('flic film', 'psychedelic 400', 400, 'color'),
('flic film', 'street savvy', 400, 'color'),
('foma', '100 classic', 100, 'bw'),
('foma', '200 creative', 200, 'bw'),
('foma', '400 action', 400, 'bw'),
('foma', 'holga 400', 400, 'bw'),
('foma', 'r100', 100, 'bw'),
('foma', 'retro 100', 100, 'bw'),
('foma', 'retro 200', 200, 'bw'),
('foma', 'retro 400', 400, 'bw'),
('foma', 'retropan 320 soft', 320, 'bw'),
('fujifilm', '200', 200, 'color'),
('fujifilm', '400', 400, 'color'),
('fujifilm', 'astia 100f', 100, 'color'),
('fujifilm', 'fp-100c', 100, 'color'),
('fujifilm', 'fujichrome provia 100', 100, 'color'),
('fujifilm', 'fujichrome t64', 100, 'color'),
('fujifilm', 'fujichrome velvia 100', 100, 'color'),
('fujifilm', 'fujichrome velvia 50', 50, 'color'),
('fujifilm', 'fujicolor c200', 200, 'color'),
('fujifilm', 'fujicolor npc 160', 160, 'color'),
('fujifilm', 'fujicolor npl 160', 160, 'color'),
('fujifilm', 'fujicolor nps 160', 160, 'color'),
('fujifilm', 'fujicolor press 400', 400, 'color'),
('fujifilm', 'fujicolor press 800', 800, 'color'),
('fujifilm', 'fujicolor pro 400h', 400, 'color'),
('fujifilm', 'fujicolor superia x-tra 400', 400, 'color'),
('fujifilm', 'fujicolor superia x-tra 800', 800, 'color'),
('fujifilm', 'instax mini', 800, 'color'),
('fujifilm', 'instax square', 800, 'color'),
('fujifilm', 'instax wide', 800, 'color'),
('fujifilm', 'neopan 400c', 400, 'bw'),
('fujifilm', 'neopan acros 100', 100, 'bw'),
('fujifilm', 'neopan ss', 100, 'bw'),
('fujifilm', 'reala 100', 100, 'color'),
('hands on film', 'after hours 800', 800, 'color'),
('hands on film', 'autumn 200', 200, 'color'),
('hands on film', 'midnight 1600', 1600, 'color'),
('hands on film', 'spring 200', 200, 'color'),
('hands on film', 'summer 400', 400, 'color'),
('harmon', 'phoenix 200', 200, 'color'),
('harmon', 'phoenix 200 II', 200, 'color'),
('harmon', 'red 125', 125, 'color'),
('ilford', 'delta 100', 100, 'bw'),
('ilford', 'delta 3200', 3200, 'bw'),
('ilford', 'delta 400', 400, 'bw'),
('ilford', 'fp4 plus', 125, 'bw'),
('ilford', 'hp5 plus', 400, 'bw'),
('ilford', 'ortho plus', 80, 'bw'),
('ilford', 'p3', 400, 'bw'),
('ilford', 'p4', 400, 'bw'),
('ilford', 'pan 100', 100, 'bw'),
('ilford', 'pan 400', 400, 'bw'),
('ilford', 'pan f plus', 50, 'bw'),
('ilford', 'sfx 200', 200, 'bw'),
('ilford', 'xp2 super', 400, 'bw'),
('japan camera hunter', 'streetpan 400', 400, 'bw'),
('kentmere', '100', 100, 'bw'),
('kentmere', '400', 400, 'bw'),
('kodak', 'aerochrome', 400, 'color'),
('kodak', 'aerocolor', 100, 'color'),
('kodak', 'colorplus 200', 200, 'color'),
('kodak', 'double-x', 200, 'bw'),
('kodak', 'ektachrome e100', 100, 'color'),
('kodak', 'ektar 100', 100, 'color'),
('kodak', 'gold 200', 200, 'color'),
('kodak', 'kodachrome 200', 200, 'color'),
('kodak', 'kodachrome 25', 25, 'color'),
('kodak', 'kodachrome 40', 40, 'color'),
('kodak', 'kodachrome 64', 64, 'color'),
('kodak', 'max 400', 400, 'color'),
('kodak', 'max 800', 800, 'color'),
('kodak', 'portra 160', 160, 'color'),
('kodak', 'portra 400', 400, 'color'),
('kodak', 'portra 800', 800, 'color'),
('kodak', 'pro image 100', 100, 'color'),
('kodak', 't-max 100', 100, 'bw'),
('kodak', 't-max 400', 400, 'bw'),
('kodak', 't-max p3200', 3200, 'bw'),
('kodak', 't400 cn', 400, 'bw'),
('kodak', 'tri-x 400', 400, 'bw'),
('kodak', 'ultramax 400', 400, 'color'),
('kodak', 'ultramax 800', 800, 'color'),
('kodak', 'vision3 200t', 200, 'color'),
('kodak', 'vision3 250d', 250, 'color'),
('kodak', 'vision3 500t', 500, 'color'),
('kodak', 'vision3 50d', 200, 'color'),
('kono', 'alien 200', 200, 'color'),
('kono', 'color 200', 200, 'color'),
('kono', 'katz 200', 200, 'color'),
('kono', 'liebe 200', 200, 'color'),
('kono', 'luft 200', 200, 'color'),
('kono', 'monolit 400', 400, 'bw'),
('kono', 'monolit 64', 64, 'bw'),
('kono', 'original candy 200', 200, 'color'),
('kono', 'original galaxy 200', 200, 'color'),
('kono', 'original mirage 200', 200, 'color'),
('kono', 'original monsoon 200', 200, 'color'),
('kono', 'original moonstruck 200', 200, 'color'),
('kono', 'original sunstroke 200', 200, 'color'),
('kono', 'rotwild no. 2', 100, 'color'),
('kono', 'ufo 200', 200, 'color'),
('kosmo foto', 'mono', 100, 'bw'),
('lomography', '100', 100, 'color'),
('lomography', '400', 400, 'color'),
('lomography', '800', 800, 'color'),
('lomography', 'berlin kino', 400, 'bw'),
('lomography', 'earl grey', 100, 'bw'),
('lomography', 'lady grey', 400, 'bw'),
('lomography', 'lomochrome color ''92', 400, 'color'),
('lomography', 'lomochrome metropolis', 100, 'color'),
('lomography', 'lomochrome purple xr', 100, 'color'),
('lomography', 'lomochrome turquoise', 100, 'color'),
('lomography', 'potsdam kino', 100, 'bw'),
('lomography', 'redscale xr', 100, 'color'),
('marix', '100d', 100, 'color'),
('marix', '320t', 320, 'color'),
('marix', '400d', 400, 'color'),
('marix', '800t', 800, 'color'),
('nocolorstudio', 'no.10 infrared', 100, 'bw'),
('nocolorstudio', 'no.10 wide spectrum', 100, 'bw'),
('optik oldschool', 'opticolour 200', 200, 'color'),
('original wolfen', 'nc200', 200, 'color'),
('original wolfen', 'nc400', 400, 'color'),
('original wolfen', 'nc500', 400, 'color'),
('original wolfen', 'np100', 100, 'bw'),
('original wolfen', 'p400', 400, 'bw'),
('original wolfen', 'un54', 100, 'bw'),
('polaroid', 'b&w i-type', 640, 'bw'),
('polaroid', 'color 600', 640, 'color'),
('polaroid', 'color i-type', 640, 'color'),
('popho', 'luminar 100', 100, 'color'),
('psychedelic blues', '400 #2', 400, 'color'),
('psychedelic blues', '400 #3', 400, 'color'),
('psychedelic blues', '400 #4', 400, 'color'),
('psychedelic blues', '400 #5', 400, 'color'),
('psychedelic blues', '400 #6', 400, 'color'),
('psychedelic blues', '400 #7', 400, 'color'),
('reflx labs', '200t', 200, 'color'),
('reflx labs', '400d', 400, 'color'),
('reflx labs', '800t', 800, 'color'),
('reflx labs', 'pro100', 100, 'color'),
('reto project', 'retocolor amber d100', 100, 'color'),
('reto project', 'retocolor amber d400', 400, 'color'),
('reto project', 'retocolor amber t200', 200, 'color'),
('reto project', 'retocolor amber t800', 800, 'color'),
('reto project', 'retocolor aqua 400', 400, 'color'),
('reto project', 'retocolor glow 400', 400, 'color'),
('reto project', 'retocolor maple 100', 100, 'color'),
('reto project', 'retocolor mosaic 100', 100, 'color'),
('reto project', 'retocolor prism 200', 200, 'color'),
('reto project', 'retocolor prism 400', 400, 'color'),
('revolog', '460nm 200', 200, 'color'),
('revolog', '600nm 200', 200, 'color'),
('revolog', 'kolor 200', 200, 'color'),
('revolog', 'kosmos 200', 200, 'color'),
('revolog', 'lazer 200', 200, 'color'),
('revolog', 'nebula 200', 200, 'color'),
('revolog', 'plexus 200', 200, 'color'),
('revolog', 'rasp 200', 200, 'color'),
('revolog', 'snovlox 100', 100, 'bw'),
('revolog', 'streak 200', 200, 'color'),
('revolog', 'tesla 1 200', 200, 'color'),
('revolog', 'tesla 2 200', 200, 'color'),
('revolog', 'texture 200', 200, 'color'),
('revolog', 'volvox 200', 200, 'color'),
('rollei', 'copex rapid', 50, 'bw'),
('rollei', 'infrared 400', 400, 'bw'),
('rollei', 'ortho 25', 25, 'bw'),
('rollei', 'retro 400', 400, 'bw'),
('rollei', 'retro 80', 80, 'bw'),
('rollei', 'rpx 100', 100, 'bw'),
('rollei', 'rpx 25', 25, 'bw'),
('rollei', 'rpx 400', 400, 'bw'),
('rollei', 'superpan 200', 200, 'bw'),
('santafilm', 'santacolor 100', 100, 'color'),
('shanghai film', 'gp3 100', 100, 'bw'),
('silbersalz35', '200t', 200, 'color'),
('silbersalz35', '250d', 250, 'color'),
('silbersalz35', '500t', 500, 'color'),
('silbersalz35', '50d', 50, 'color'),
('whatevergraphy', 'retrochrome 320', 320, 'color'),
('yes!star', 'supreme 200', 200, 'color'),
('yes!star', 'supreme 400', 400, 'color'),
('yodica', 'andromeda 400', 400, 'color'),
('yodica', 'antares 400', 400, 'color'),
('yodica', 'atlas 400', 400, 'color'),
('yodica', 'callisto 400', 400, 'color'),
('yodica', 'pegasus 400', 400, 'color'),
('yodica', 'polaris 400', 400, 'color'),
('yodica', 'vega 400', 400, 'color');

INSERT INTO cameras (camera_make, camera_model, description)
SELECT camera_make, camera_model, camera_make || ' ' || camera_model
FROM bench_cameras
ORDER BY camera_make, camera_model;

INSERT INTO films (film_make, film_type, film_speed, color_type, description)
SELECT film_make, film_type, film_speed, color_type, film_make || ' ' || film_type
FROM bench_films
ORDER BY film_make, film_type, film_speed;

-- popularity rank: a fixed shuffle, sampled with a skew so a few models dominate
CREATE TEMP TABLE bench_camera_rank ON COMMIT DROP AS
SELECT (row_number() OVER (ORDER BY md5(camera_make || '/' || camera_model)) - 1)::int AS rn, camera_make, camera_model
FROM bench_cameras;

CREATE TEMP TABLE bench_film_rank ON COMMIT DROP AS
SELECT (row_number() OVER (ORDER BY md5(film_make || '/' || film_type || '/' || film_speed)) - 1)::int AS rn, film_make, film_type, film_speed
FROM bench_films;

CREATE TEMP TABLE bench_words ON COMMIT DROP AS
SELECT ARRAY[
  'beach', 'sunset', 'portrait', 'street', 'city', 'night', 'mountain', 'forest', 'lake', 'river',
  'morning', 'evening', 'winter', 'summer', 'autumn', 'spring', 'snow', 'rain', 'fog', 'light',
  'shadow', 'window', 'door', 'car', 'train', 'bridge', 'road', 'field', 'flower', 'tree',
  'dog', 'cat', 'bird', 'friend', 'mother', 'father', 'sister', 'brother', 'girl', 'boy',
  'house', 'church', 'tower', 'harbor', 'boat', 'sea', 'ocean', 'island', 'desert', 'canyon',
  'valley', 'hill', 'garden', 'park', 'market', 'cafe', 'bar', 'kitchen', 'bedroom', 'studio',
  'grain', 'color', 'contrast', 'double', 'exposure', 'self', 'first', 'roll', 'last', 'frame',
  'tokyo', 'paris', 'london', 'berlin', 'new york', 'rome', 'lisbon', 'seoul', 'mexico', 'iceland',
  'quiet', 'golden', 'blue', 'hour', 'old', 'new', 'little', 'big', 'long', 'lonely',
  'home', 'trip', 'road trip', 'wedding', 'concert', 'festival', 'protest', 'crowd', 'alley', 'rooftop'
] AS w;

CREATE TEMP TABLE bench_vocab ON COMMIT DROP AS
SELECT w || ARRAY(SELECT 'term' || g FROM generate_series(1, 3000 - array_length(w, 1)) g) AS v
FROM bench_words;

CREATE TEMP TABLE bench_colors ON COMMIT DROP AS
SELECT
  ARRAY['gray', 'black', 'white', 'brown', 'tan', 'teal', 'olive', 'navy', 'green', 'orange', 'red', 'yellow', 'purple'] AS html,
  ARRAY['dimgray', 'black', 'gainsboro', 'saddlebrown', 'wheat', 'steelblue', 'darkolivegreen', 'midnightblue', 'seagreen', 'coral', 'firebrick', 'khaki', 'violet'] AS css;

-- one row of random draws per post, materialized so ids and values stay deterministic
CREATE TEMP TABLE bench_posts ON COMMIT DROP AS
SELECT
  i,
  random() AS r_time,
  random() AS r_score,
  random() AS r_author,
  random() AS r_nsfw,
  random() AS r_grey,
  random() AS r_sprocket,
  random() AS r_desc,
  random() AS r_cam_null,
  random() AS r_cam,
  random() AS r_film_null,
  random() AS r_film,
  random() AS r_focal,
  random() AS r_aperture,
  random() AS r_shape,
  random() AS r_comma,
  1 + floor(random() * 100)::int AS t1,
  1 + floor(random() * 100)::int AS t2,
  1 + floor(random() * 100)::int AS t3,
  1 + floor(random() * 100)::int AS t4,
  floor(random() * 4)::int AS t_len,
  5 + floor(random() * 11)::int AS n_keywords
FROM generate_series(1, :posts) i;

INSERT INTO pictures (
  url, title, author, permalink, description, score, nsfw, greyscale, time, width, height, sprocket,
  lowurl, lowwidth, lowheight, medurl, medwidth, medheight, highurl, highwidth, highheight,
  camera_make, camera_model, film_make, film_type, film_speed, focal_length, aperture
)
SELECT
  'https://bench.analogdb.test/raw/' || p.i || '.jpeg',
  initcap(w.w[p.t1]) || CASE WHEN p.r_comma < 0.2 THEN ', ' ELSE ' ' END || w.w[p.t2]
    || CASE WHEN p.t_len >= 1 THEN ' ' || w.w[p.t3] ELSE '' END
    || CASE WHEN p.t_len >= 2 THEN ' ' || w.w[p.t4] ELSE '' END
    || ' [' || coalesce(c.camera_make || ' ' || c.camera_model, 'unknown') || ' | ' || coalesce(f.film_make || ' ' || f.film_type, 'film') || ']',
  'u/author' || floor(10000 * power(p.r_author, 2))::int,
  'https://www.reddit.com/r/analog/comments/bench' || p.i || '/',
  CASE WHEN p.r_desc < 0.3 THEN 'shot on ' || coalesce(c.camera_make, 'a camera') || ', developed at home' END,
  floor(3000 * power(p.r_score, 4))::int,
  p.r_nsfw < 0.02,
  p.r_grey < 0.15,
  -- about five years ending at a fixed time
  1790000000 - floor(p.r_time * 157680000)::int,
  s.width,
  s.height,
  p.r_sprocket < 0.05,
  'https://bench.analogdb.test/low/' || p.i || '.jpeg', 720, (720 * s.height / s.width),
  'https://bench.analogdb.test/med/' || p.i || '.jpeg', 1080, (1080 * s.height / s.width),
  'https://bench.analogdb.test/high/' || p.i || '.jpeg', 1440, (1440 * s.height / s.width),
  c.camera_make,
  c.camera_model,
  f.film_make,
  f.film_type,
  f.film_speed,
  CASE WHEN p.r_focal < 0.6 THEN (ARRAY[28, 35, 40, 50, 50, 50, 80, 85, 105, 135])[1 + floor(p.r_focal / 0.6 * 10)::int] END,
  CASE WHEN p.r_aperture < 0.4 THEN (ARRAY['f/1.4', 'f/2', 'f/2.8', 'f/4', 'f/5.6', 'f/8', 'f/11', 'f/16'])[1 + floor(p.r_aperture / 0.4 * 8)::int] END
FROM bench_posts p
CROSS JOIN bench_words w
CROSS JOIN LATERAL (
  SELECT
    CASE WHEN p.r_shape < 0.55 THEN 4000 WHEN p.r_shape < 0.85 THEN 2667 ELSE 3000 END AS width,
    CASE WHEN p.r_shape < 0.55 THEN 2667 WHEN p.r_shape < 0.85 THEN 4000 ELSE 3000 END AS height
) s
LEFT JOIN bench_camera_rank c
  ON p.r_cam_null >= 0.2
  AND c.rn = floor(power(p.r_cam, 2.5) * (SELECT count(*) FROM bench_camera_rank))::int
LEFT JOIN bench_film_rank f
  ON p.r_film_null >= 0.25
  AND f.rn = floor(power(p.r_film, 2.5) * (SELECT count(*) FROM bench_film_rank))::int
ORDER BY p.i;

-- five colors per post, percents sum to about 1 and are stored in descending order
CREATE TEMP TABLE bench_post_colors ON COMMIT DROP AS
SELECT p.i, k, random() AS r_share, random() AS r_html
FROM bench_posts p
CROSS JOIN generate_series(1, 5) k
ORDER BY p.i, k;

INSERT INTO colors (hex, css, html, percent, post_id)
SELECT
  '#' || substr(md5(x.i || '/' || x.k), 1, 6),
  bc.css[x.idx],
  bc.html[x.idx],
  round((x.r_share / sum(x.r_share) OVER (PARTITION BY x.i))::numeric, 8),
  x.i
FROM (
  SELECT i, k, r_share, 1 + floor(power(r_html, 1.6) * 13)::int AS idx
  FROM bench_post_colors
) x
CROSS JOIN bench_colors bc
ORDER BY x.i, x.r_share DESC;

-- about ten keywords per post from a skewed vocabulary
CREATE TEMP TABLE bench_post_keywords ON COMMIT DROP AS
SELECT p.i, 1 + floor(3000 * power(random(), 3))::int AS idx, random() AS r_weight
FROM bench_posts p
CROSS JOIN LATERAL generate_series(1, p.n_keywords) k
ORDER BY p.i, k;

INSERT INTO keywords (word, weight, post_id)
SELECT word, weight, i
FROM (
  SELECT DISTINCT ON (x.i, v.v[x.idx]) x.i, v.v[x.idx] AS word, round(x.r_weight::numeric, 8) AS weight
  FROM bench_post_keywords x
  CROSS JOIN bench_vocab v
  ORDER BY x.i, v.v[x.idx], x.r_weight DESC
) d
ORDER BY i, weight DESC, word;

INSERT INTO post_updates (post_id, score_update_time, keywords_update_time)
SELECT id, time + 86400, time + 86400
FROM pictures
WHERE id % 20 = 0
ORDER BY id;

COMMIT;

VACUUM ANALYZE pictures;
VACUUM ANALYZE keywords;
VACUUM ANALYZE colors;
VACUUM ANALYZE post_updates;
VACUUM ANALYZE cameras;
VACUUM ANALYZE films;
