syntax = "proto3";

package analytics;

option go_package = "github.com/evanofslack/analogdb/internal/gen/proto/analytics/v1;analyticsv1";
option java_package = "com.evanofslack.analogdb.analytics";
option java_multiple_files = true;

message Event {
  string request_id = 1;
  string remote_ip = 2;
  string url = 3;
  string path = 4;
  string protocol = 5;
  string scheme = 6;
  string method = 7;
  string user_agent = 8;
  int32 response_code = 9;
  string hostname = 10;
  bool authorized = 11;
  int64 start_time = 12;
  int64 end_time = 13;
  int64 request_time_ms = 14;
  int32 bytes_in = 15;
  int32 bytes_out = 16;
}

