version: "3.8"

networks:
  default:
    external: true
    name: analogdb

services:
  web:
    build:
      context: ./
      target: runner
    container_name: analogdb-web
    ports:
      - "${WEB_BIND_ADDR:-127.0.0.1}:3000:3000"
    environment:
      - API_WEB_USERNAME=${API_WEB_USERNAME}
      - API_WEB_PASSWORD=${API_WEB_PASSWORD}
      - API_ADMIN_USERNAME=${API_ADMIN_USERNAME}
      - API_ADMIN_PASSWORD=${API_ADMIN_PASSWORD}
