version: "3.8"

networks:
  default:
    external: true
    name: analogdb

services:
  web:
    build:
      context: ./
      target: runner
    container_name: analogdb-web
    ports:
      - "3000:3000"
